import {
  BABEL_CONFIG,
  CODECOV_CONFIG,
  COMMITLINT_CONFIG,
  EDITOR_CONFIG,
  ESLINT_CONFIG,
  ESLINT_IGNORE,
  GIT_IGNORE,
  JEST_CONFIG,
  JS_EXT,
  LERNA_CONFIG,
  LICENSE,
  MARKDOWN_EXT,
  MARKDOWN_LINT_CONFIG,
  NODE_VERSION,
  NPMRC,
  PACKAGE_JSON_FILENAME,
  PRETTIER_CONFIG,
  README,
  ROLLUP_CONFIG,
  STYLELINT_CONFIG,
  TRAVIS_CONFIG,
  TSCONFIG,
  TSCONFIG_SETTINGS,
  TSLINT_CONFIG,
  TYPEDOC_CONFIG,
} from "./files";
import {
  BABEL_CONFIG_PKG,
  BUILD_REFERENCES_PKG,
  CODECOV,
  COMMITLINT_CONFIG_PKG,
  ESLINT_CONFIG_PKG,
  JEST_CONFIG_PKG,
  LERNA_CONFIG_PKG,
  MARKDOWN_LINT_CONFIG_PKG,
  NEW_PACKAGE_PKG,
  PRETTIER_CONFIG_PKG,
  ROLLUP_CONFIG_PKG,
  STYLELINT_CONFIG_PKG,
  TSLINT_CONFIG_PKG,
  TS_CONFIG_PKG,
  TS_JEST,
  TS_TOOLBELT,
  TYPEDOC_CONFIG_PKG,
  TYPES_FS_EXTRA,
  TYPES_JEST,
  TYPES_LODASH,
  TYPES_NODE,
  TYPE_FEST,
  UTILITY_TYPES,
} from "./pkgs";

export const TERMINAL_ECHO_PREFIX = ">>>>>>";

export const FILE_ENCODING = "utf8";

export const DUPLICATE = "duplicate";
export const FAIL = "fail";
export const MERGE = "merge";
export const OVERWRITE = "overwrite";
export const ACCEPT = "accept";
export const REJECT = "reject";

export const COPY_BEHAVIOUR_EXISTING_FILE = {
  DUPLICATE,
  FAIL,
  MERGE,
  OVERWRITE,
};

export const COPY_BEHAVIOUR = {
  ACCEPT,
  REJECT,
};

export const DEST_INTO_SCAFFOLD = "destIntoScaffold";
export const SCAFFOLD_INTO_DEST = "scaffoldIntoDest";

export const MERGE_STRATEGY = {
  DEST_INTO_SCAFFOLD,
  SCAFFOLD_INTO_DEST,
};

export const BROWSER = "browser";
export const CSS = "css";
export const MONOREPO = "monorepo";
export const REACT = "react";
export const TYPESCRIPT = "typescript";

export const REPO_FEATURES = [BROWSER, CSS, MONOREPO, REACT, TYPESCRIPT];

export const REPO_FEATURES_TO_SCAFFOLD_FILE_NAMES = {
  [BROWSER]: [ROLLUP_CONFIG],
  [CSS]: [STYLELINT_CONFIG],
  [MONOREPO]: [LERNA_CONFIG],
  [REACT]: [],
  [TYPESCRIPT]: [TSCONFIG, TSCONFIG_SETTINGS, TSLINT_CONFIG, TYPEDOC_CONFIG],
};

export const FILE_NAMES_EXCLUDED_FROM_MERGE = [LICENSE];

export const EXTS_EXCLUDED_FROM_MERGE = [JS_EXT, MARKDOWN_EXT];

export const BASE_REPO_PKGS = [
  BABEL_CONFIG_PKG,
  CODECOV,
  COMMITLINT_CONFIG_PKG,
  ESLINT_CONFIG_PKG,
  JEST_CONFIG_PKG,
  MARKDOWN_LINT_CONFIG_PKG,
  PRETTIER_CONFIG_PKG,
];

export const REPO_FEATURES_TO_REPO_PKGS = {
  [BROWSER]: [ROLLUP_CONFIG_PKG],
  [CSS]: [STYLELINT_CONFIG_PKG],
  [MONOREPO]: [LERNA_CONFIG_PKG, NEW_PACKAGE_PKG],
  [REACT]: [],
  [TYPESCRIPT]: [
    [BUILD_REFERENCES_PKG, { dependantOn: [MONOREPO] }],
    TS_CONFIG_PKG,
    TSLINT_CONFIG_PKG,
    TYPEDOC_CONFIG_PKG,
  ],
};

export const FILE_NAMES_TO_PKG_NAMES = {
  [BABEL_CONFIG]: [BABEL_CONFIG_PKG],
  [CODECOV_CONFIG]: [CODECOV],
  [COMMITLINT_CONFIG]: [COMMITLINT_CONFIG_PKG],
  [EDITOR_CONFIG]: [],
  [ESLINT_CONFIG]: [ESLINT_CONFIG_PKG],
  [ESLINT_IGNORE]: [],
  [GIT_IGNORE]: [],
  [JEST_CONFIG]: [JEST_CONFIG_PKG],
  [LERNA_CONFIG]: [BUILD_REFERENCES_PKG, LERNA_CONFIG_PKG, NEW_PACKAGE_PKG],
  [LICENSE]: [],
  [MARKDOWN_LINT_CONFIG]: [MARKDOWN_LINT_CONFIG_PKG],
  [NODE_VERSION]: [],
  [NPMRC]: [],
  [PACKAGE_JSON_FILENAME]: [],
  [PRETTIER_CONFIG]: [PRETTIER_CONFIG_PKG],
  [README]: [],
  [ROLLUP_CONFIG]: [ROLLUP_CONFIG_PKG],
  [STYLELINT_CONFIG]: [STYLELINT_CONFIG_PKG],
  [TRAVIS_CONFIG]: [],
  [TSCONFIG_SETTINGS]: [
    BUILD_REFERENCES_PKG,
    TS_CONFIG_PKG,
    TS_JEST,
    TS_TOOLBELT,
    TYPES_FS_EXTRA,
    TYPES_JEST,
    TYPES_LODASH,
    TYPES_NODE,
    TYPE_FEST,
    UTILITY_TYPES,
  ],
  [TSLINT_CONFIG]: [TSLINT_CONFIG_PKG],
  [TYPEDOC_CONFIG]: [TYPEDOC_CONFIG_PKG],
};
